// Generated J1939 SPN mappings from Scania Fault codes DM1 Issue 6.0 Documentation
// https://www.scania.com/content/dam/scanianoe/market/au/products-and-services/engines/electrical-system/Fault-codes-DM1_Issue-6.pdf
// Scania CV AB 2016 - Industrial engines DC09, DC13, DC16 and Marine engines DI09, DI13, DI16

const j1939SpnMappings = {
    46: "Pneumatic Supply Pressure",
    51: "Engine Throttle Valve 1 Position", 
    91: "Accelerator Pedal Position 1",
    94: "Engine Fuel Delivery Pressure",
    97: "Water In Fuel Indicator",
    98: "Engine Oil Level",
    100: "Engine Oil Pressure",
    102: "Engine Intake Manifold #1 Pressure",
    103: "Engine Turbocharger 1 Speed",
    105: "Engine Intake Manifold 1 Temperature",
    107: "Engine Air Filter 1 Differential Pressure",
    108: "Barometric Pressure",
    110: "Engine Coolant Temperature",
    111: "Engine Coolant Level",
    131: "Engine Exhaust Back Pressure",
    132: "Engine Intake Air Mass Flow Rate",
    156: "Engine Injector Timing Rail 1 Pressure",
    167: "Charging System Potential (Voltage)",
    168: "Battery Potential/Power Input 1",
    171: "Ambient Air Temperature",
    172: "Engine Air Intake Temperature",
    174: "Engine Fuel Temperature 1",
    175: "Engine Oil Temperature 1",
    188: "Engine Speed At Idle, Point 1 (Engine Configuration)",
    190: "Engine Speed",
    234: "Software Identification",
    532: "Engine Speed At High Idle, Point 6 (Engine Configuration)",
    558: "Accelerator Pedal 1 Low Idle Switch",
    559: "Accelerator Pedal Kickdown Switch",
    590: "Engine Idle Shutdown Timer State",
    597: "Brake Switch",
    598: "Clutch Switch",
    636: "Engine Position Sensor",
    641: "Engine Variable Geometry Turbocharger Actuator #1",
    645: "Engine Tachometer Signal Output",
    651: "Engine Injector Cylinder #01",
    652: "Engine Injector Cylinder #02",
    653: "Engine Injector Cylinder #03",
    654: "Engine Injector Cylinder #04",
    655: "Engine Injector Cylinder #05",
    656: "Engine Injector Cylinder #06",
    657: "Engine Injector Cylinder #07",
    658: "Engine Injector Cylinder #08",
    677: "Engine Starter Motor Relay",
    723: "Engine Speed 2",
    968: "Engine Idle Increment Switch",
    972: "Accelerator Interlock Switch",
    974: "Remote Accelerator Pedal Position",
    986: "Requested Percent Fan Speed",
    1086: "Parking and/or Trailer Air Pressure",
    1108: "Engine Protection System Timer Override",
    1110: "Engine Protection System has Shutdown Engine",
    1135: "Engine Oil Temperature 2",
    1239: "Engine Fuel Leakage 1",
    1322: "Engine Misfire for Multiple Cylinders",
    1323: "Engine Misfire Cylinder #1",
    1324: "Engine Misfire Cylinder #2", 
    1325: "Engine Misfire Cylinder #3",
    1326: "Engine Misfire Cylinder #4",
    1327: "Engine Misfire Cylinder #5",
    1328: "Engine Misfire Cylinder #6",
    1329: "Engine Misfire Cylinder #7",
    1330: "Engine Misfire Cylinder #8",
    1442: "Engine Fuel Valve 1 Position",
    1443: "Engine Fuel Valve 2 Position",
    1483: "Source Address of Controlling Device for Engine Control",
    1484: "Other ECUs Have Reported Fault Codes Affecting Operation",
    1485: "ECM Main Relay",
    1569: "Engine Protection Torque Derate",
    1632: "Engine Torque Limit Feature",
    1639: "Fan Speed",
    1675: "Engine Starter Mode",
    1761: "Aftertreatment 1 Diesel Exhaust Fluid Tank Level",
    2609: "Cab A/C Refrigerant Compressor Outlet Pressure",
    2791: "Engine Exhaust Gas Recirculation 1 (EGR1) Valve Control",
    2797: "Engine Injector Group 1",
    2798: "Engine Injector Group 2",
    2858: "Machine Data Configuration 1",
    2859: "Machine Data Configuration 2",
    2860: "Machine Data Configuration 3",
    2861: "Machine Data Configuration 4",
    2862: "Machine Data Configuration 5",
    3031: "Aftertreatment 1 Diesel Exhaust Fluid Tank Temperature",
    3216: "Aftertreatment 1 Intake NOx",
    3226: "Aftertreatment 1 Outlet NOx",
    3241: "Aftertreatment 1 Exhaust Gas Temperature 1",
    3242: "Aftertreatment 1 Diesel Particulate Filter Intake Gas Temperature",
    3245: "Aftertreatment 1 Exhaust Gas Temperature 3",
    3246: "Aftertreatment 1 Diesel Particulate Filter Outlet Gas Temperature",
    3249: "Aftertreatment 1 Exhaust Gas Temperature 2",
    3251: "Aftertreatment 1 Diesel Particulate Filter Differential Pressure",
    3275: "Aftertreatment 2 Exhaust Gas Temperature 1",
    3279: "Aftertreatment 2 Exhaust Gas Temperature 3",
    3283: "Aftertreatment 2 Exhaust Gas Temperature 2",
    3340: "Engine Charge Air Cooler 1 Intake Pressure",
    3360: "Aftertreatment 1 Diesel Exhaust Fluid Controller",
    3361: "Aftertreatment 1 Diesel Exhaust Fluid Dosing Unit",
    3362: "Aftertreatment 1 Diesel Exhaust Fluid Dosing Unit Input Lines",
    3363: "Aftertreatment 1 Diesel Exhaust Fluid Tank Heater",
    3464: "Engine Throttle Actuator 1 Control Command",
    3471: "Aftertreatment 1 Fuel Pressure Control Actuator",
    3472: "Aftertreatment 1 Air Pressure Control Actuator", 
    3480: "Aftertreatment 1 Fuel Pressure 1",
    3485: "Aftertreatment 1 Supply Air Pressure",
    3515: "Aftertreatment 1 Diesel Exhaust Fluid Temperature 2",
    3516: "Aftertreatment 1 Diesel Exhaust Fluid Concentration",
    3563: "Engine Intake Manifold #1 Absolute Pressure",
    3607: "Engine Emergency (Immediate) Shutdown Indication",
    3673: "Engine Throttle Valve 2 Position",
    3822: "Engine Exhaust Gas Recirculation 1 Valve 2 Position",
    3936: "Aftertreatment Diesel Particulate Filter System",
    4090: "NOx limits exceeded, root cause unknown",
    4094: "NOx limits exceeded due to Insufficient Diesel Exhaust Fluid Quality",
    4095: "NOx limits exceeded due to Interrupted Diesel Exhaust Fluid Dosing",
    4096: "NOx limits exceeded due to Empty Diesel Exhaust Fluid Tank",
    4201: "Engine Speed 1",
    4202: "Engine Speed 3",
    4225: "NOx limits exceeded due to error in the NOx control system",
    4301: "Aftertreatment 1 Fuel Injector 1 Heater Control",
    4334: "Aftertreatment 1 Diesel Exhaust Fluid Doser Absolute Pressure",
    4337: "Aftertreatment 1 Diesel Exhaust Fluid Dosing Temperature",
    4341: "Aftertreatment 1 Diesel Exhaust Fluid Line Heater 1 Preliminary FMI",
    4343: "Aftertreatment 1 Diesel Exhaust Fluid Line Heater 2 Preliminary FMI",
    4345: "Aftertreatment 1 Diesel Exhaust Fluid Line Heater 3 Preliminary FMI",
    4347: "Aftertreatment 1 Diesel Exhaust Fluid Line Heater 4 Preliminary FMI",
    4374: "Aftertreatment 1 Diesel Exhaust Fluid Pump Motor Speed",
    4427: "Aftertreatment 2 Diesel Exhaust Fluid Tank Temperature",
    4782: "Diesel Particulate Filter 1 Soot Density",
    4809: "Aftertreatment 1 Warm Up Diesel Oxidation Catalyst Intake Temperature",
    4810: "Aftertreatment 1 Warm Up Diesel Oxidation Catalyst Outlet Temperature",
    4814: "Engine Coolant Pump command",
    5264: "Engine Exhaust Gas Recirculation 2 (EGR2) Valve Control",
    5265: "Engine Exhaust Gas Recirculation 2 (EGR2) Valve 2 Control",
    5285: "Engine Charge Air Cooler 1 Efficiency",
    5401: "Engine Turbocharger Turbine Bypass Actuator",
    5419: "Engine Throttle Actuator 1",
    5421: "Engine Turbocharger Wastegate Actuator 1",
    5435: "Aftertreatment 1 Diesel Exhaust Fluid Pump State",
    5485: "Aftertreatment 1 Diesel Exhaust Fluid Pump Orifice Flow",
    5541: "Engine Turbocharger 1 Turbine Outlet Pressure",
    5543: "Engine Exhaust Brake Actuator Command",
    5706: "Aftertreatment 1 Diesel Exhaust Fluid Pump Heater",
    5743: "Aftertreatment Selective Catalytic Reduction Temperature Sensor Module",
    5745: "Aftertreatment 1 Diesel Exhaust Fluid Dosing Unit Heater",
    5841: "Diesel Exhaust Fluid Quality Malfunction"
};

// FMI (Failure Mode Identifier) mappings from Scania documentation
const j1939FmiMappings = {
    0: "Data valid but above normal operational range (that is, engine overheating)",
    1: "Data valid but below normal operational range (that is, engine oil pressure too low)",
    2: "Data erratic, intermittent, or incorrect",
    3: "Voltage above normal or shorted high",
    4: "Voltage below normal or shorted low",
    5: "Current below normal or open circuit",
    6: "Current above normal or grounded circuit",
    7: "Mechanical system not responding properly",
    8: "Abnormal frequency, pulse width, or pending",
    9: "Abnormal update rate",
    10: "Abnormal rate of change",
    11: "Failure mode not identifiable",
    12: "Bad intelligent device or component",
    13: "Out of calibration",
    14: "Special instructions",
    15: "Data valid but above normal operating range - least severe level",
    16: "Data valid but above normal operating range - moderately severe level", 
    17: "Data valid but below normal operating range - least severe level",
    18: "Data valid but below normal operating range - moderately severe level",
    19: "Received network data in error",
    20: "Data drifted high",
    21: "Data drifted low"
};

module.exports = {
    spnMappings: j1939SpnMappings,
    fmiMappings: j1939FmiMappings
}; 